server:
  port: 8081

spring:
  profiles:
    active: service
  redis:
    host: localhost
    port: 6379

logging:
  file:
    max-history: 10
    max-size: 10MB
  path: log/log.log

feign:
  okhttp:
    enabled: true