server:
  port: 8083

spring:
  profiles:
    active: service
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 500MB
      # 总大小
      max-request-size: 10GB

# 监控监控
management:
  server:
    port: 8084
  endpoints:
    web:
      base-path: /monitor
      #加载所有的端点/默认只加载了info/health
      exposure:
        include: "*"

logging:
  file:
    max-history: 10
    max-size: 10MB
  path: log/log.log

feign:
  okhttp:
    enabled: true

file:
  parentPath: /Users/zzy/Desktop/file/
