server:
  port: 9000

spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    include: service

logging:
  level:
    root: info

chat:
  registerAsServer: true
  coderType: DELIMITER
  server:
    port: 10000
    autoRestartTimeInterval: 5
  client:
    center:
      host: localhost
      port: 10000
      autoRestartTimeInterval: 5
    commonServer:
      port: 10003
      autoRestartTimeInterval: 5
    webServer:
      port: 10004
      autoRestartTimeInterval: 5