server:
  port: 9003

spring:
  profiles:
    include: service
  redis:
    host: localhost
    port: 6379

# 监控监控
management:
#  server:
#    port: 8082
  endpoints:
    web:
      base-path: /monitor

logging:
  level:
    root: info

chat:
  registerAsServer: false
  coderType: DELIMITER
  server:
    port: 10000
    autoRestartTimeInterval: 5
  client:
    center:
      host: localhost
      port: 10000
      autoRestartTimeInterval: 5
    commonServer:
      port: 10003
      autoRestartTimeInterval: 5
    webServer:
      port: 10004
      autoRestartTimeInterval: 5