spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    include: service

chat:
  registerAsServer: false
  coderType: STRING
  server:
    port: 10000
    autoRestartTimeInterval: 5
  client:
    center:
      host: localhost
      port: 10000
      autoRestartTimeInterval: 5
    commonServer:
      port: 10001
      autoRestartTimeInterval: 5
    webServer:
      port: 10002
      autoRestartTimeInterval: 5
