server:
  port: 10002

spring:
  profiles:
    include: service
  redis:
    host: localhost
    port: 6379

# 监控监控
management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: "*"

logging:
  level:
    root: debug

chat:
  registerAsServer: false
  coderType: DELIMITER
  server:
    port: 20000
    autoRestartTimeInterval: 5
  client:
    center:
      host: localhost
      port: 20000
      autoRestartTimeInterval: 5
    commonServer:
      port: 20001
      autoRestartTimeInterval: 5
    webServer:
      port: 20002
      autoRestartTimeInterval: 5