spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    include: service

chat:
  registerAsServer: false
  server:
    port: 10000
#    autoRestartTimeInterval: 5
  client:
    host: localhost
    port: 10001
    port2: 10002
